### ISSUE TITLE
Block blob upload fails with large files

### ISSUE THREAD

**Issue by udf2457** [Azure/azure-storage-php#187] opened 2019-05-04 20:50 UTC
As mentioned in #185 , I have been encountering the below error when uploading large files (e.g. 70+GB).

> In CurlFactory.php line 186:
> cURL error 56: (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

I can confirm this is due to something bad in your code.   Even if I use `$blobClient->setSingleBlobUploadThresholdInBytes()` and `$blobClient->setBlockSize(` it still doesn't work.

 Because I have created a very crude script of my own (see below) and it uploads large files without issse.

Therefore please run tests on your code using large files.

```
<?php
require("/etc/foo/vendor/autoload.php");
$uri="https://*****.blob.core.windows.net";
$sas='*********';
$azureVersion="2018-03-28";
$sourceBlob="/srv/tmp/x/filename";
$destPath="/dll/foo";
$blockList=array();
$blockList[]='<?xml version="1.0" encoding="utf-8"?>';
$blockList[]='<BlockList>';
$somethingFailed=false;

$guzzle = new GuzzleHttp\Client (['timeout'=>30]);


$fh=fopen($sourceBlob,'rb');

do {    
    $blockID=base64_encode(openssl_random_pseudo_bytes(64));
    $buf=fread($fh,100000000);
    $blockMD5=base64_encode(md5($buf,true));
    $headers=[
        'Content-Length' => strlen($buf),
        'Content-MD5' => $blockMD5,
        'x-ms-version' => $azureVersion,
        'x-ms-date' => date('r')
        
    ];
    $request = new GuzzleHttp\Psr7\Request('PUT', $uri.$destPath."?comp=block&blockid=".rawurlencode($blockID)."&".$sas,$headers,$buf);
    $response = $guzzle->send($request);
    $code = $response->getStatusCode();
    $reason = $response->getReasonPhrase();
    if ($code===201) {
        $blockList[]='<Uncommitted>'.$blockID.'</Uncommitted>';
    } else {
        $somethingFailed=true;
        echo "retrying !".PHP_EOL;
        sleep(random_int(3,5));
        $headers['x-ms-date']=date('r');
        $response = $guzzle->send($request);
        $code = $response->getStatusCode(); 
        $reason = $response->getReasonPhrase(); 
        if ($code===201) {
            $blockList[]='<Uncommitted>'.$blockID.'</Uncommitted>';
            $somethingFailed=false;
        } else {
            echo "upload failed !";
            exit(1);
        }
    }
} while (!feof($fh));

$blockList[]='</BlockList>';


$headers=[
        'Content-Length' => strlen(implode($blockList)),
        'Content-MD5' => base64_encode(md5(implode($blockList),true)),
        'x-ms-version' => $azureVersion,
        'x-ms-date' => date('r')
        
];
$request = new GuzzleHttp\Psr7\Request('PUT', $uri.$destPath."?comp=blocklist&".$sas,$headers,implode($blockList));
$response = $guzzle->send($request);
    $code = $response->getStatusCode(); 
    $reason = $response->getReasonPhrase(); 
    if ($code===201) {
        echo "UPLOAD COMPLETE !".PHP_EOL;
    } else {
        $somethingFailed=true;
        echo "retrying !".PHP_EOL;
        sleep(random_int(3,5));
        $headers['x-ms-date']=date('r');
        $response = $guzzle->send($request);
        $code = $response->getStatusCode(); 
        $reason = $response->getReasonPhrase(); 
        if ($code===201) {
            echo "UPLOAD COMPLETE !".PHP_EOL;
            $somethingFailed=false;
        } else {
            echo "upload failed !";
            exit(1);
        }
    }
```

**Comment by XiaoningLiu** [comment] 2019-05-05 03:45
In our previous large scale testing (TB level), we didn't get this kind of network errors. Will see if it's a bug in SDK. Can you set a lower upload concurrency for a try to see if it avoid the network errors? As mentioned in #142, customized retry decider can also be provided to define which kind of exceptions should be retried.

**Comment by udf2457** [comment] 2019-05-05 07:30
@XiaoningLiu Thanks for your reply. However I can confirm it is not network errors due to issues on my side.  My code uploaded all blocks on the first attempt, there were no retries required of any blocks.

**Comment by XiaoningLiu** [comment] 2019-05-06 02:02
That's weird, because SDK also depends on Guzzle for request sending. According to libcurl error code definition, error 56 is "CURLE_RECV_ERROR (56) Failure with receiving network data.". Unluckily, I cannot reproduce it in my environment.

**Comment by RobDonovan** [comment] 2019-06-05 19:42
Hi, 

Not sure if this is also the same as my problem or not.

For the last 5 years, I have a script run that uploads my backups from my Linux VM to Blob storage.

This months 'full' backup will not write to the blob storage for some reason, since 1st May.

I know it's a very crude script, but it's been working  for 5 years :)

`$blobRestProxy = ServicesBuilder::getInstance()->createBlobService($connectionString);

$file = $argv[2];

$content = fopen($file, "r");
$blob_name = $argv[3];
$container = $argv[1];

$md5 = base64_encode(md5_file($file,true));

$blobOptions = new CreateBlobOptions();

if (isset($options['cachecontrol'])) {
        $blobOptions->setBlobCacheControl($options['cachecontrol']);
}
if (isset($options['contenttype'])) {
        $blobOptions->setBlobContentType($options['contenttype']);
}
if (isset($options['contentencoding'])) {
        $blobOptions->setBlobContentEncoding($options['contentencoding']);
}

$blobOptions->setBlobContentMD5($md5);

try {
  //Upload blob
  $blobRestProxy->createBlockBlob($container, $blob_name, $content, $blobOptions);
  exit(0);
} catch(ServiceException $e){
  $code = $e->getCode();
  $error_message = $e->getMessage();
  echo $code.": ".$error_message."\n";
  exit(3);
}
`

After a while it errors with this:
`PHP Warning:  fwrite(): SSL: Connection reset by peer in /home/system/www/phpLibs/azure/HTTP/Request2/SocketWrapper.php on line 202
PHP Fatal error:  Uncaught HTTP_Request2_MessageException: Error writing request in /home/system/www/phpLibs/azure/HTTP/Request2/Adapter/Socket.php on line 981
#0 /home/system/www/phpLibs/azure/HTTP/Request2/Adapter/Socket.php(981): HTTP_Request2_SocketWrapper->write('?o????3????p???...')
#1 /home/system/www/phpLibs/azure/HTTP/Request2/Adapter/Socket.php(144): HTTP_Request2_Adapter_Socket->writeBody()
#2 /home/system/www/phpLibs/azure/HTTP/Request2.php(941): HTTP_Request2_Adapter_Socket->sendRequest(Object(HTTP_Request2))
#3 /home/system/www/phpLibs/azure/WindowsAzure/Common/Internal/Http/HttpClient.php(262): HTTP_Request2->send()
#4 /home/system/www/phpLibs/azure/WindowsAzure/Common/Internal/RestProxy.php(141): WindowsAzure\Common\Internal\Http\HttpClient->send(Array, Object(WindowsAzure\Common\Internal\Http\Url))
#5 /home/system/www/phpLibs/azure/WindowsAzure/Common/Internal/ServiceRestProxy.php(86): WindowsAzure\Common\Internal\RestProxy->sendContext(Object(WindowsAzure\Common\Internal\Http\HttpCallContext))
#6 /home/system in /home/system/www/phpLibs/azure/HTTP/Request2/SocketWrapper.php on line 206
`

The file I'm trying to upload is 1,271,366,361 bytes in size, which although is a few mb more than last months, still fairly typical to what I have uploaded every month with no problems before.

In testing, a file 700000000 bytes uploads fine, but a file 800000000 gets the error.

The problem must have started sometime between 02/May and 01/June, as before then it worked fine. 

Is this similar? Or helpful at all?

Thanks, Rob.

**Comment by XiaoningLiu** [comment] 2019-06-13 09:02
Sorry for late response. @RobDonovan Does this still happen? Connection reset usually means network broken.

**Comment by RobDonovan** [comment] 2019-06-13 11:08
> Sorry for late response. @RobDonovan Does this still happen? Connection reset usually means network broken.

No problem. :)
I just tried it, and now it's all working. (It was directly from my Azure VM -> blob-storage, so I'm guessing something was wrong your network side).
Thanks for sorting it! :)

**Comment by katmsft** [comment] 2020-01-03 02:32
Since the issue is now resolved, we will close this issue. Thanks for reporting it!

**Closed** 2020-01-06 05:56 UTC
Labels: investigation, question, v2020Jan
