### ISSUE TITLE
copyBlob generates incorrect x-ms-copy-source header

### ISSUE THREAD

**Issue by Rambomst** [Azure/azure-storage-php#41] opened 2016-11-03 22:39 UTC
When using copyBlob it will generate a full URI however when it calls the method getUri it will return a string that ends in a `/`. Since containerNames must start with a `/` this causes a double up of slashes for the header value.

It currently generates like
`https://something.blob.core.windows.net//1234/photo/1.png`

However it should be
`https://something.blob.core.windows.net/1234/photo/1.png`

**Comment by katmsft** [comment] 2016-11-18 07:16
I failed to reproduce your problem without a further clarification.
Please leave comments of what the source container name/destination container name you are using and provide the code snippet that can reproduce your problem if possible. Thanks.

I ran the test with the following code and it just worked correctly.

```
// Setup
$sourceContainerName = 'copyblobdiffcontainerssource';
$sourceBlobName = 'sourceblob';
$blobValue = 'testBlobValue';
$destinationContainerName = 'copyblobdiffcontainersdestination';
$destinationBlobName = 'destinationblob';
$blobClient->createContainer($sourceContainerName);
$blobClient->createContainer($destinationContainerName);
$blobClient->createBlockBlob(
    $sourceContainerName,
    $sourceBlobName,
    $blobValue
);

// Test
$result = $blobClient->copyBlob(
    $destinationContainerName,
    $destinationBlobName,
    $sourceContainerName,
    $sourceBlobName
);

// Assert
$sourceBlob = $blobClient->getBlob($sourceContainerName, $sourceBlobName);
$destinationBlob = $blobClient->getBlob($destinationContainerName, $destinationBlobName);
$sourceBlobContent = stream_get_contents($sourceBlob->getContentStream());
$destinationBlobContent =
    stream_get_contents($destinationBlob->getContentStream());

echo "source content {$sourceBlobContent}\n";
echo "destin content {$destinationBlobContent}\n";
$etag = $result->getETag();
echo "etag {$etag}\n";
```

**Comment by Rambomst** [comment] 2016-11-20 21:53
`$destinationContainer = /s123456`
`$destinationBlob = documents/school/12312/1_families.txt;1.0`
`$sourceContainer = /s123456`
`$sourceBlob = documents/school/1231/1_families.txt;1.0`

If I remove the `/` from the start of the container name it will throw an error saying it is required. 

Error when running copyBlob:

`There was an error renaming the file. Error 400: Fail:
Code: 400
Value: The value for one of the HTTP headers is not in the correct format.
details (if any): ﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format.
RequestId:3c826c8a-0001-003c-4b77-432d14000000
Time:2016-11-20T21:49:07.0595677Z</Message><HeaderName>x-ms-copy-source</HeaderName><HeaderValue>https://xxxx.blob.core.windows.net//s123456/documents/school/1231/1_families.txt%3B1.0</HeaderValue></Error>.`

**Comment by katmsft** [comment] 2016-11-21 02:59
The problem which SDK crashes when user input a container start with a `slash` is addressed and will be fixed in the next release. However I still could not trigger the error that you have of 'If I remove the `/` from the start of the container name it will throw an error saying it is required.'
`copyBlob` does not seem to have any logic that requires user to put a `/` in the front of a container name, nor does `createContainer`. Any chance you could tell me what function call you made that throws this exception?

**Comment by Rambomst** [comment] 2016-11-21 03:27
The exact error it gives is `The path of a URI with an authority must start with a slash "/" or be empty` and it looks like the error is coming from Guzzle, here is a stacktrace.

```
#0 /usr/test/vendor/guzzlehttp/psr7/src/Uri.php(502): GuzzleHttp\Psr7\Uri->validateState()
#1 /usr/test/vendor/microsoft/azure-storage/src/Common/Internal/ServiceRestProxy.php(124): GuzzleHttp\Psr7\Uri->withPath('s123456')
#2 /usr/test/vendor/microsoft/azure-storage/src/Blob/BlobRestProxy.php(1181): MicrosoftAzure\Storage\Common\Internal\ServiceRestProxy->send('GET', Array, Array, Array, 's123456', 200)
#3 /usr/test/www/_inc/classes/storage/provider/azure_blob.class.php(181): MicrosoftAzure\Storage\Blob\BlobRestProxy->listBlobs('s123456', Object(MicrosoftAzure\Storage\Blob\Models\ListBlobsOptions))
#4 {main}
```

**Comment by katmsft** [comment] 2016-11-21 03:33
Thanks for the detail, I will look into this. Because my code sample does not call `listBlobs` and maybe that is why this error is not reproduced.

**Comment by katmsft** [comment] 2016-11-21 07:56
Could you provide the version of your Guzzle?

**Comment by Rambomst** [comment] 2016-11-21 20:57
```
guzzle/parser                      v3.9.2
guzzlehttp/guzzle                  dev-master 0118099
guzzlehttp/promises                1.2.0
guzzlehttp/psr7                    dev-master 64862e8
```

**Comment by katmsft** [comment] 2016-11-22 01:43
It seems that the problem is indeed with the Guzzle's new implementation of `Uri->validateState()`, which was merged into the master branch of its repository but not yet released. This repository uses the release version of Guzzle and that is why we did not catch any problem when we ran the tests. For now it would require you to download the release version of Guzzle via Composer to work around this issue.

**Comment by katmsft** [comment] 2017-01-20 02:27
Suggest to close as this issue is addressed in 0.12.0.

**Comment by vinjiang** [comment] 2017-01-20 09:08
@Rambomst we have an implementation in [0.12.0](https://github.com/Azure/azure-storage-php/releases/tag/v0.12.0) to address this 'future' issue. Feel free to have a try and let us know if you have further questions.

**Closed by vinjiang** 2017-01-20 09:08 UTC

**Comment by hoangmnsd** [comment] 2020-11-18 09:36
i'm getting into this issue on azure cli 2.15 (windows subsystem Ubuntu 18.04 LTS)
`azure-cli                         2.15.0

core                              2.15.0
telemetry                          1.0.6

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\lhhoang\.azure\cliextensions'

Python (Windows) 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy`
