### ISSUE TITLE
Issues after migrating from Azure SDK for PHP

### ISSUE THREAD

**Issue by jvegaseg** [Azure/azure-storage-php#149] opened 2018-07-12 15:56 UTC
We was using Azure SDK for PHP for blobs during a lot of time without problems. After upgrading to Azure-Storage-PHP we get errors randomly like:

- cURL error 56: SSL read: errno -5961
- cURL error 7: Failed connect to xxxx.blob.core.windows.net:443; Operation now in progress

Is this library ready for production?
Why I get those errors?

Regards,

**Comment by lksnmnn** [comment] 2018-07-25 16:04
Hey there.
We also see random cURL errors when checking if a blob exists.
```
cURL error 56: SSL read: error:00000000:lib(0):func(0):reason(0), errno 104 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) {"exception":"[object] (GuzzleHttp\\Exception\\RequestException(code: 0): cURL error 56: SSL read: error:00000000:lib(0):func(0):reason(0), errno 104 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) at .../vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186)
```
I will check our php.ini against the README and update this comment...

**Comment by katmsft** [comment] 2018-07-26 01:23
In the Readme.md there are following lines:
```
Required extension for PHP:

php_fileinfo.dll
php_mbstring.dll
php_openssl.dll
php_xsl.dll
Recommended extension for PHP:

php_curl.dll
```
Please take a a look.

As for the cURL errors, the error indicates that the server has reset the TCP connection. The best way to continue is to retry on this scenario.

**Comment by lksnmnn** [comment] 2018-07-26 07:19
We have those extensions installed. So this shouldn't be the issue here.

But why does Azure Blob Storage resets the TCP connection? We have to upload blobs between 5MB and 2 GB. In order to do this we chunk the data first and then send it into storage. 
The connection reset always happens during `getBlobMetadata` in the `BlobRestProxy`, when we check if there are already parts of the blob written.

Sorry for hijacking this issue. I will try to add a retry mechanism, but I believe, the connection shouldn't be reset that often in the first place ?!

**Comment by katmsft** [comment] 2018-07-27 06:34
Can you provide a sample code that can solidly reproduce this issue? I will work with service team to find out why this happens all the time.

**Comment by lksnmnn** [comment] 2018-07-27 07:58
Weirdly enough, this only happens in one of our environments. I will dig into it and see if I can spot the difference. If not, I will provide a small example.

**Comment by katmsft** [comment] 2018-07-30 02:02
Great to see that this issue is resolved. @jvegaseg Can you also try this and see if the issue is caused by mis-match of dependencies?

**Comment by lksnmnn** [comment] 2018-08-05 14:45
Hey @katmsft. 

I wanted to let you know, that we increased our _php-fpm_ timeouts, which masked some of the errors we were seeing. Now, we do get random connect errors to the Blob Storage. Just as @jvegaseg.

We opened a high prio ticket and talked to a support engineer last week. He suggested to make sure that storage and application are in the same region (which they are), update the framework to the latest version (we used 1.1.0) and implement the suggested retry middleware.

Now, instead of getting connect errors, we get a crash in the RetryMiddlewareFactory:
```
[2018-08-03 17:20:27] stage.ERROR: Call to a member function getStatusCode() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getStatusCode() on null at /var/www/storage_app/releases/20180803071211Z/vendor/microsoft/azure-storage-common/src/Common/Middlewares/RetryMiddlewareFactory.php:171)
```

I will update to 1.2.0 and test again.

By the way, this is not the only network related issue we have with Azure services. Both DB and Redis have a terrible latency which makes using certain ORMs super slow, since they make many small database requests and latency / network has a bigger impact on performance.

**Comment by spaze** [comment] 2018-08-29 13:27
@lksnmnn about the error message

```
Call to a member function getStatusCode() on null [...] RetryMiddlewareFactory.php:171
```

I've fixed that and added connection retries in https://github.com/Azure/azure-storage-php/issues/147 and it was released in [microsoft/azure-storage-common 1.2.0](https://github.com/Azure/azure-storage-php/releases/tag/v1.2.0-common). I see you've updated to 1.2.0 but not sure you've update also the common package. Check you've update also microsoft/azure-storage-common to 1.2.0.

**Comment by lksnmnn** [comment] 2018-08-30 16:07
Yes, since we require `microsoft/azure-storage-blob": "~1.2.0"` the correct commons packages is installed. See this snipped of the composer.lock:

```
   {
            "name": "microsoft/azure-storage-common",
            "version": "1.2.0",
             ...       
```

Indeed, the offending line is fixed in the file in my vendor folder. So this exception should not occur anymore. But I will test this again as soon as I have some time :)

**Comment by katmsft** [comment] 2020-01-03 02:41
Since the customer does not provide any further update, this issue will now be closed. Feel free to reopen or submit another issue if any.

**Closed** 2020-01-06 06:34 UTC
Labels: question, v2020Jan
