### ISSUE TITLE
Container name with incorrect <space> causes Mac Validation error

### ISSUE THREAD

**Issue by nowenL** [Azure/azure-storage-php#4] opened 2016-04-21 08:43 UTC
Migrated from: Azure/azure-sdk-for-php#798

I incorrectly tried to call listBlobs with a container name that had a space in it "uploaded files" instead of "uploadedfiles", which is an illegal name. I would have expected a straight-forward exception to be thrown but instead, was shown the dreaded: The MAC signature found in the HTTP request ... is not the same as any computed signature.

This took me hours to fix because it looked like a much more serious error than it really was (did I need to manually compute the signature etc.).

I guess that any API call that requires a conforming name to be passed for container or blob name should validate the format in the SDK and throw an exception rather than pass the call to the API. It would also be nice if the API itself returned a more useful error but that is someone else's problem.

**Comment by katmsft** [comment] 2017-04-06 07:39
Hi, after tried with latest server version, which is 2016-05-31, I found that the error message changed to this:
The specifed resource name contains invalid characters.

I believe this is good enough, but still the SDK is using 2015-04-05 so the problem is actually not fixed. After we catch up the feature gap and decide to bump up the version, we will let you know. Sorry for the inconvenience.

**Comment by katmsft** [comment] 2017-08-03 09:09
Issue resolved after version 1.0.0-beta.1. Suggest to close the issue.

**Closed** 2017-08-03 09:23 UTC

**Comment by katmsft** [comment] 2017-08-04 07:31
The version `1.0.0-beta.1` will be recalled, and will be changed to version 0.17.0. The product code will not change but the `user-agent` string and tag will be changed.
