### ISSUE TITLE
Error Code 100 createBlockBlob

### ISSUE THREAD

**Issue by markusleadsuite** [Azure/azure-storage-php#180] opened 2019-04-02 16:29 UTC
### Which service(blob, file, queue, table) does this issue concern?
->Blob

### Which version of the SDK was used?
-> "microsoft/azure-storage-blob": "^1.2"

### What's the PHP/OS version?
-> PHP: 7.2 
-> Windows Server 2012 R2 with IIS 8.5
-> Laravel 5.2

### What problem was encountered?
When trying to createBlockBlob sometimes the following error is thrown. The request takes more then 5 minutes and then closes with the error. 

[2019-04-01 14:01:43] production.ERROR: MicrosoftAzure\Storage\Common\Exceptions\ServiceException: Fail:
Code: 100
Value: Continue
details (if any): . in D:\Solution\Solution\vendor\microsoft\azure-storage-common\src\Common\Internal\ServiceRestProxy.php:490
Stack trace:
#0 D:\Solution\Solution\vendor\microsoft\azure-storage-common\src\Common\Internal\ServiceRestProxy.php(406): MicrosoftAzure\Storage\Common\Internal\ServiceRestProxy::throwIfError(Object(GuzzleHttp\Psr7\Response), 201)
#1 D:\Solution\Solution\vendor\guzzlehttp\promises\src\Promise.php(203): MicrosoftAzure\Storage\Common\Internal\ServiceRestProxy->MicrosoftAzure\Storage\Common\Internal\{closure}(Object(GuzzleHttp\Exception\RequestException))
#2 D:\Solution\Solution\vendor\guzzlehttp\promises\src\Promise.php(174): GuzzleHttp\Promise\Promise::callHandler(2, Object(GuzzleHttp\Exception\RequestException), Array)
#3 D:\Solution\Solution\vendor\guzzlehttp\promises\src\RejectedPromise.php(40): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}(Object(GuzzleHttp\Exception\RequestException))
#4 D:\Solution\Solution\vendor\guzzlehttp\promises\src\TaskQueue.php(47): GuzzleHttp\Promise\RejectedPromise::GuzzleHttp\Promise\{closure}()
#5 D:\Solution\Solution\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(98): GuzzleHttp\Promise\TaskQueue->run()
#6 D:\Solution\Solution\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(125): GuzzleHttp\Handler\CurlMultiHandler->tick()
#7 D:\Solution\Solution\vendor\guzzlehttp\promises\src\Promise.php(246): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
#8 D:\Solution\Solution\vendor\guzzlehttp\promises\src\Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#9 D:\Solution\Solution\vendor\guzzlehttp\promises\src\Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#10 D:\Solution\Solution\vendor\guzzlehttp\promises\src\Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#11 D:\Solution\Solution\vendor\guzzlehttp\promises\src\Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#12 D:\Solution\Solution\vendor\microsoft\azure-storage-blob\src\Blob\BlobRestProxy.php(1755): GuzzleHttp\Promise\Promise->wait()
#13 D:\Solution\Solution\app\Jobs\Azure\Azure.php(75): MicrosoftAzure\Storage\Blob\BlobRestProxy->createBlockBlob('8uavlrcoxeb2634...', 'CR7KXsPwUzYpxaT...', Resource id #189)
### Have you found a mitigation/solution?
-> Not yet

Best regards
Markus

**Comment by XiaoningLiu** [comment] 2019-04-03 03:05
@markusleadsuite 

Can you disable 100-continue feature and try again? See http://docs.guzzlephp.org/en/stable/request-options.html#expect

```php
$options['http'] = ['expect' => false]; // Disable validation entirely

$blobClient = BlobRestProxy::createBlobService(
    $connectionString,
    $options
);
```

**Comment by markusleadsuite** [comment] 2019-04-03 06:59
Hey @XiaoningLiu, 

thank you very much. This solved the error but then an other error appears:

production.ERROR: GuzzleHttp\Exception\RequestException: cURL error 56: OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054

But then I realized that I didn't installed the php_xsl.dll extension. After I added this one to the php.ini the problem was gone ;)

**Comment by XiaoningLiu** [comment] 2019-04-04 02:38
@markusleadsuite Glad to know that!

**Comment by katmsft** [comment] 2020-01-03 02:34
Since the problem is now resolved we will close the issue. Thanks for raising the question!

**Closed** 2020-01-06 05:57 UTC
Labels: question, v2020Jan
